# Site settings
title: John Li - Software Engineer
description: "John's sweet home in the Internet world"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://www.zhuoran.li"
# User settings
username: John Li
user_title: John Li - Software Engineer
email: zhuoran666@gmail.com
linkedin_site_id: john-li-zhuoran
github_username:  lzhuor
twitter_username: lzhuor
disqus_username: lzhuor
profile_picture: /assets/img/avatar.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
encoding: utf-8

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: babel-plugin-react-intl
    url: https://github.com/yahoo/babel-plugin-react-intl
  - name: girtech-farewell-revealjs
    url: https://github.com/lzhuor/girtech-farewell-revealjs
  - name: facebook-page-language-analysis
    url: https://github.com/lzhuor/facebook-page-language-analysis
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
