name: John Li (@lzr911) 

title: Hello John!

description: Software Engineer with a passion for understanding things at a fundamental.

linkedin_url: https://www.linkedin.com/in/john-li-zhuoran/

gir_tech_life_url: http://www.girtech.sg

theme: jekyll-theme-cayman
